### ISSUE TITLE
Flatpak build

### ISSUE THREAD

**Issue by LeandroStanger** [TechnicPack/LauncherV3#119]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing Technic Launcher on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by casept** [comment]
@LeandroStanger I have started working on this at https://github.com/casept/LauncherV3/tree/flatpak. Main issues remaining are:

1. Maven build script integration (not sure if/how I'll integrate it, seems like a massively painful DSL).
2. Actually being able to test it properly with a source-built launcher. I seem to be getting a `401` from the API, but it works fine if you copy-paste a release binary from the website.
3. Appstream metadata and all the other little polish stuff.

**Comment by LeandroStanger** [comment]
Consider publishing Technic Launcher on Flathub
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by Pyker** [comment]
Thank you for the suggestion and the comments, but we won't be creating a Flatpak package for Technic Launcher due to limitations with Java and Flatpak dependencies. You can read about a similar request at https://github.com/MultiMC/MultiMC5/issues/3149#issuecomment-628603996

**Comment by alvarlagerlof** [comment]
Has this potentially changed in the last to years? I made a prototype here: https://github.com/alvarlagerlof/net.technicpack.TechnicLauncher. It managed open the game but will not install modpacks.

**Comment by Pyker** [comment]
Appreciate the prototype, but this hasn't changed.
