### ISSUE TITLE
Don't create coremods folder if not needed

### ISSUE THREAD

**Issue by ghost** [TechnicPack/LauncherV3#128]
You shouldn't auto create the coremods folder if it's not needed. It would be a simple check to not create it (Float.valueOf(the first 3 numbers of getMinecraft()) > (whatever minecraft version that was). I'd do that myself, but I am not sure if you use the folder in other tasks as to rip it out properly.

**Comment by Pyker** [comment]
The amount of work this requires is too high, considering the outcome is one directory less in the modpack's folder. There are no side effects to having that folder there.
