### ISSUE TITLE
versions.json always downloads from Minecraft Libraries

### ISSUE THREAD

**Issue by Kio-td** [TechnicPack/LauncherV3#133]
I've been working on crafting a custom Solder version, that enables the use of FabricMC.

They suggest using version.json for technic- which I have been doing. However, when attempting to have my modpack properly download, it errors out after attempting to download it from
https://libraries.minecraft.net/net/fabricmc/yarn/1.15.2/yarn-1.15.2.jar.

I'm just a tad bit confused, because I thought it would acknowledge Fabric's custom URL.

**Comment by Kio-td** [comment]
When I run Fabric as a config file zip, it runs normally. To say the least, _this is confusing._

**Comment by Pyker** [comment]
This should work properly now
