### ISSUE TITLE
Incorrect java version check

### ISSUE THREAD

**Issue by brezinajn** [TechnicPack/LauncherV3#134]
Current version of the launcher won't launch on GraalVM. 
It gives error: `This application requires a Java Runtime Environment 1.8.0 - 1.8.0_999`
My java environment: 
```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 25.242-b06-jvmci-20.0-b02, mixed mode)
```

**Comment by Pyker** [comment]
Launch4j uses the registry to find out what Java versions it has available. Make sure that when you install, you enable the option to register that JRE in the registry.

**Comment by brezinajn** [comment]
GraalVM doesn't really come with an installer. Is there an option to specify JRE in an argument, external config or env variable?

**Comment by brezinajn** [comment]
Closing this since it's issue with launch4j not with not with the Technic Launcher. Lack of possibility to specify JRE for launch4j exe basically means it only supports oracle jre. Workaround for anyone interested: Use launcher version "for Linux" afaict it's just simple jar without any platform dependency.
