### ISSUE TITLE
java.lang.UnsupportedOperationException: PERPIXEL_TRANSLUCENT translucency is not supported

### ISSUE THREAD

**Issue by bothie** [TechnicPack/LauncherV3#143]
I get this exception

java.lang.UnsupportedOperationException: PERPIXEL_TRANSLUCENT translucency is not supported
        at java.awt.Window.setBackground(Window.java:3844)
        at java.awt.Dialog.setBackground(Dialog.java:1359)
        at net.technicpack.ui.controls.LauncherDialog.<init>(LauncherDialog.java:37)
        [...]

In LauncherV3/src/main/java/net/technicpack/ui/controls/LauncherDialog.java, i see:

        try {
            this.setBackground(new Color(0, 0, 0, 0));
            getRootPane().setBorder(new DropShadowBorder(Color.black, 4));
        } catch (IllegalArgumentException ex) {
            //OS doesn't support translucent windows- dumb dumb dumb
            //Eat it and just don't do the drop shadow
        }

So, I guess, another catch for java.lang.UnsupportedOperationException is needed here.

**Comment by phit** [comment]
introduced in https://github.com/TechnicPack/LauncherV3/commit/b983b1481751bbb563012e7e89add90e2747e548#diff-6be80ead67105dfb0453a4ba5a8c6b22R37 to fix https://github.com/TechnicPack/LauncherUICore/issues/8

**Comment by Pyker** [comment]
So, this error is coming from an outdated cracked launcher?

**Comment by phit** [comment]
no, you arent catching the right exception

**Comment by Pyker** [comment]
Oh. I'll write a fix for it later today then.

**Comment by Pyker** [comment]
Ah, the LauncherDialogue class is missing this exception

**Comment by Pyker** [comment]
Thanks @bothie for the bug report, and @phit for the help. :)

**Comment by Pyker** [comment]
This has been deployed to the beta branch (build 557)
