### ISSUE TITLE
Set default page/tab/menu when loading.

### ISSUE THREAD

**Issue by notl3ks** [TechnicPack/LauncherV3#186]
It would be nice if the launcher had an option to load a set default page when starting the launcher.

For example the option to have "modpacks" be the page that loads when starting the launcher.

**Comment by Pyker** [comment]
It literally already is an option, check the launcher settings.

**Comment by notl3ks** [comment]
> 
> 
> It literally already is an option, check the launcher settings.

Can you show me where? I can't seem to find such option.

**Comment by Pyker** [comment]
Just in case anyone else reading the thread is wondering: 
![image](https://user-images.githubusercontent.com/528849/119873422-705c0380-bf1c-11eb-8954-9197d6efee45.png)
