### ISSUE TITLE
"Add Microsoft Login" web server is blocking

### ISSUE THREAD

**Issue by Pyker** [TechnicPack/LauncherV3#193]
When logging in with a new account, the logic behind the "Add Microsoft Login" button that does the actual OAuth authentication (with the local server and waiting for the user to login) runs in the Event Dispatch Thread, which means that the entire UI freezes until the user logs in successfully.

**Comment by vorburger** [comment]
I'm hitting this as well, and more than "UI freezes" for me it actually prevents logging in all together... thus blocking me from migrating to Microsoft account (and keep using Technic Launcher).  At least on Fedora 34, under both Wayland as well as X11 sessions, with OpenJDK 11, with both Firefox and (Chromium-based) Brave, it only opens that MS OAuth https://login.live.com/oauth20_authorize.srf page AFTER I xkill Technic Launcher, so there's some race condition here... of course when I login after killing launcher, it obviously 404s on the localhost Jetty. https://gist.github.com/vorburger/6b8863be11f0474f10f8515cd196f35a has the `jstack`. Long story short, this makes it impossible to use Techniclauncher, for me.

I'll see if it would be easy to help fix this.

**Comment by vorburger** [comment]
#242 offers a possible solution for this bug. It does the trick for me on on Linux (simply by giving preferences to using `xdg-open` over `Desktop.getDesktop().browse()`).

https://github.com/TechnicPack/LauncherV3/compare/master...vorburger:bug-193_SwingWorker was an alternative that I explored to use a `SwingWorker` in `DesktopUtils`'s `browseUrl()` just like it already does for `open()` - but that does not do the trick (for the problem I'm seeing).

Another approach may be to more fundamtenally rework the threading logic involved here, but that's a bit more work.

**Comment by Pyker** [comment]
Just had someone else on Fedora 35 confirm that they're seeing the same behavior: launcher freezing when trying to login with Microsoft account, and the browser window opening *after* the launcher is killed.

**Comment by tomodachi94** [comment]
> It does the trick for me on on Linux (simply by giving preferences to using xdg-open over `Desktop.getDesktop().browse())`.

Per [this SO answer](https://stackoverflow.com/a/23039509), it looks like we can call `explorer https://example.com` on Windows and `open https://example.com` on Mac for the same effect as `xdg-open https://example.com`.

**Comment by tomodachi94** [comment]
Ah, hmm, looks like I misinterpreted the issue. It looks like Jetty, the library that is being used to host the server, has good async support (according to [this blog](https://www.baeldung.com/jetty-embedded)).

**Comment by Pyker** [comment]
Fixed in c56c5ca255f423e810b4c7878e1b3ef7507378b6
