### ISSUE TITLE
Setting memory in RunData to high enough values results in NPE

### ISSUE THREAD

**Issue by Jaari** [TechnicPack/LauncherV3#209]
If you set the memory in RunData to a value >=16385, modpacks won't start and the usual requirement warning window will not pop up, instead resulting in a NPE in the log:

> [B#693] 2021/09/20 09:32:27 [SEVERE] java.lang.NullPointerException
[B#693] 2021/09/20 09:32:27 [SEVERE] 	at net.technicpack.utilslib.Memory.getClosestAvailableMemory(Memory.java:73)
[B#693] 2021/09/20 09:32:27 [SEVERE] 	at net.technicpack.launchercore.modpacks.RunData.getValidMemory(RunData.java:84)
[B#693] 2021/09/20 09:32:27 [SEVERE] 	at net.technicpack.launcher.ui.components.FixRunDataDialog.recommendSettings(FixRunDataDialog.java:96)
[B#693] 2021/09/20 09:32:27 [SEVERE] 	at net.technicpack.launcher.ui.components.FixRunDataDialog.<init>(FixRunDataDialog.java:52)
[B#693] 2021/09/20 09:32:27 [SEVERE] 	at net.technicpack.launcher.launch.Installer$1.run(Installer.java:145)
[B#693] 2021/09/20 09:32:27 [SEVERE] 	at java.lang.Thread.run(Unknown Source)

Whether this is because my system doesn't have more than 16GB RAM (16384) or because the maximum memory option is 16 GB, I don't know.

**Comment by Pyker** [comment]
15 GB is the RAM cap in the launcher, even if your system has more (so people don't overallocate). This is an interesting bug.

**Comment by Pyker** [comment]
Should be just a null check for https://github.com/TechnicPack/LauncherV3/blob/0b5e377d2efa5d4710b7bce82ceaaa93fe9a2b9b/src/main/java/net/technicpack/launchercore/modpacks/RunData.java#L83. Should probably also limit runData max memory to the launcher max, 16 GB.
