### ISSUE TITLE
Minotar API Doesn't handle Transparent skin 

### ISSUE THREAD

**Issue by 1fxe** [TechnicPack/LauncherV3#263]
We can switch to a different API (Cravatar) for example or wait till Minotar fixes it (idk when this will happen I could open issue there)? 
Minotar
![Minotar](https://minotar.net/helm/glDrawArrays/100.png)

![image](https://user-images.githubusercontent.com/37674069/167505115-d9a34679-523e-4d95-a9cf-ad57a7c60c6c.png)

Cravatar
![cravatar](https://cravatar.eu/helmavatar/glDrawArrays/100.png)

**Comment by Pyker** [comment]
This isn't really a problem with the launcher, seems like it's a problem with Minotar, according to what you're saying.

**Comment by Pyker** [comment]
Some more context: we have actually switched away from Crafatar to Minotar a few years ago (https://github.com/TechnicPack/LauncherV3/commit/d62852a2748524c0a71fd89a9659a7932facfe70), so we could continue to use both usernames and UUIDs (Crafatar started rejecting any username-based requests).

**Comment by 1fxe** [comment]
@Pyker I'll open an issue on imgd (Minotar) and see if they plan to fix it. We can close this issue I think

**Comment by Pyker** [comment]
Alright 👍🏼

**Comment by 1fxe** [comment]
Update: Fixed 😄 
![image](https://user-images.githubusercontent.com/37674069/168180388-2c5f2700-82f0-4492-b95f-b408028cbac2.png)

**Comment by Pyker** [comment]
That was really fast, damn.

**Comment by LukeHandle** [comment]
@1fxe did all the work, the least I could do was deploy it! Thanks for reaching out 👍
