### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by jordsta95** [TechnicPack/LauncherV3#29]
This is more of an issue with the website than the launcher, but this is the only place I have found where I can contact people on the Technic team semi-directly (less publicly)
The About Us area on the website does not display any contact information, which could be very bad should someone come to you about a business enquiry, or something similar. For example, I spent 10 minutes looking through the website, then went to the Technic Twitter and Facebook pages, still nothing, so GitHub was my last port of call.
In the grand scheme of things what I wanted to enquire about wasn't that big, but what someone else might want to talk about could be huge, whether it be a sponsorship deal, partnership deal, or a merging deal (e.g. Curse and Technic working together).

Again, sorry about this being in TOTALLY the wrong place, but it was the only place I could assume it would seen.

**Comment by sct** [comment]
Some things have gotten lost in all the fuss of the launch including a proper contact page. I threw up something that at least gets people the correct info until something better can replace it. Thanks for pointing it out though.
