### ISSUE TITLE
Have the launcher pull lib files for old minecraft versions

### ISSUE THREAD

**Issue by zlepper** [TechnicPack/LauncherV3#32]
It has come to my attention that really old versions of minecraft 1.5.2 and before requires some lib files forge automatically downloads, which aren't available anymore. This renders most older packs unusable unless people have some other way of getting those files. 
So maybe you need some way to have the launcher get those files from another place if an older version of minecraft is detected.

**Comment by CannibalVox** [comment]
Hi, unfortunately I could not reproduce this issue.  I was able to wipe my technic install and run the recommended versions of tekkit classic, tekkit lite, and voltz without issues.  Can you provide a set of steps from a fresh install?

**Comment by zlepper** [comment]
nvm. Seems issue is no longer happening.
