### ISSUE TITLE
Use XDG standard directories instead of directory of JAR for logging, data storage

### ISSUE THREAD

**Issue by tomodachi94** [TechnicPack/LauncherV3#322]
The launcher should use XDG standard directories for data and log storage (in `~/.local`) instead of the directory where the JAR is located.

This is an issue for packaging with the Nix package manager, as the JAR lands in the read-only 'Nix store' instead of a user-writable directory like `~/Downloads`.

The data should be placed in `%AppData%` on Windows and `~/Library/Application Support` on MacOS.

(Related: https://github.com/NixOS/nixpkgs/pull/239652)

**Comment by tomodachi94** [comment]
I can write a patch for this, I'd just like to know if a patch would be welcome before beginning work.

**Comment by Pyker** [comment]
Appreciate the offer, but if changes are needed for this I'll write them myself.

I'm unsure of what you mean, since the launcher does in fact store data in the places you already mentioned: `%appdata%\.technic` for Windows, `~/.technic` for Linux and `~/Library/Application Support/technic` for MacOS: https://github.com/TechnicPack/LauncherV3/blob/2ea377bb81d6fe6a393c790fb659a134a571f03e/src/main/java/net/technicpack/utilslib/OperatingSystem.java#L72-L92

**Comment by Pyker** [comment]
Also I want to point out that the ONLY authorized distribution point of our launcher is via https://www.technicpack.net/download, and anything else either won't work or won't be supported.

**Comment by tomodachi94** [comment]
> I'm unsure of what you mean, since the launcher does in fact store data in the places you already mentioned: `%appdata%\.technic` for Windows, `~/.technic` for Linux and `~/Library/Application Support/technic` for MacOS

I get this output in the (non-Technic) console when running the launcher:

```
Settings for exe: /nix/store/znsfn97vhh8fhdld3g7yj2kc31cz6nl2-technic-launcher-1.6.56/share/java/technic-launcher-1.6.56.jar
Portable settings dir: /nix/store/znsfn97vhh8fhdld3g7yj2kc31cz6nl2-technic-launcher-1.6.56/share/java/technic
```

I think I misinterpreted these log entries. I'll edit the issue title shortly to reflect the actual issue.

**Comment by Pyker** [comment]
You did. Those are merely debug messages for the eventuality that portable mode is being used.

**Comment by tomodachi94** [comment]
My bad, closing.
