### ISSUE TITLE
[Feature] Launcher/Solder Multi-File Download and Reassembly

### ISSUE THREAD

**Issue by Brycey92** [TechnicPack/LauncherV3#35]
I hereby request the ability to specify certain groups of files in solder that would be downloaded and reassembled into 1 file in the modpack directory. For example, I have a 32mb audio resource litemod that I don't want users to have to redownload every time I add a music file to it. Instead, ideally, I would add another file to the group in solder. Upon updating the pack, the launcher would download this small file, and repack it with the other files of the same group that are already in the modpack's cache folder.

Related feature requests:
https://github.com/TechnicPack/TechnicSolder/issues/293
https://github.com/TechnicPack/TechnicSolder/issues/294
https://github.com/TechnicPack/LauncherV3/issues/36

**Comment by Brycey92** [comment]
https://github.com/TechnicPack/LauncherV3/issues/35

**Comment by Brycey92** [comment]
https://github.com/TechnicPack/TechnicSolder/issues/293

**Comment by Brycey92** [comment]
Please unstale this, stalebot!

**Comment by Pyker** [comment]
Thanks, but this won't be implemented. If you're using Solder properly then you already can do something like this (split up your audio files into different "mods").
