### ISSUE TITLE
[Feature] Download Resource Packs and Inessential Mods After Initial Download

### ISSUE THREAD

**Issue by Brycey92** [TechnicPack/LauncherV3#36]
In addition to my earlier request, I propose a feature where the launcher downloads essential mods and allows the user to launch the pack, but continues to download files such as resource packs and other large inessential files. Such files would be marked in solder as something like "post-initial-download."

If my other feature, Launcher/Solder Multi-File Download and Reassembly, is implemented, I also request compatibility with this feature, for even more streamlined modpack deployments.

Related feature requests:
https://github.com/TechnicPack/TechnicSolder/issues/294
https://github.com/TechnicPack/LauncherV3/issues/35
https://github.com/TechnicPack/TechnicSolder/issues/293

**Comment by Brycey92** [comment]
Please unstale this, bot-san!

**Comment by Pyker** [comment]
As mentioned in TechnicPack/TechnicSolder#293, it makes no sense to implement this because this is not how Minecraft works and it would result in broken modpacks.
