### ISSUE TITLE
Fonts not being installed

### ISSUE THREAD

**Issue by aglarcz** [TechnicPack/LauncherV3#371]
Launcher is trying to load Raleway+FireflySung.ttf and OpenSans+Cyberbit.ttf from assets/launcher folder but those are not installed there, producing error with java.io.FileNotFoundException.

**Comment by Pyker** [comment]
That always happens the first time the launcher runs, but that error message doesn't happen afterwards.

**Comment by aglarcz** [comment]
In fact it does happen again - I just tried to install the launcher as admin but fonts are still not installed. Windows 10 64bit.

**Comment by Pyker** [comment]
Something about your setup is broken. Also, it's really not recommended to run the launcher with admin permissions.

**Comment by aglarcz** [comment]
I have tried to install via newest version now and its okay. So yup, problem on my side.
