### ISSUE TITLE
error compiling with maven

### ISSUE THREAD

**Issue by Marcus89uk** [TechnicPack/LauncherV3#45]
Hello. Could you explain what this error means 

[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Technic Launcher 4.0-0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for net.technicpack:launchercore:jar:2.0.0-SNAPSHOT is missing
, no dependency information available
[WARNING] The POM for net.technicpack:launcheruicore:jar:1.0-SNAPSHOT is missing
, no dependency information available
[WARNING] The POM for net.technicpack:minecraftcore:jar:1.0.0-SNAPSHOT is missin
g, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.900 s
[INFO] Finished at: 2015-05-13T22:54:46+01:00
[INFO] Final Memory: 10M/113M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project launcher: Could not resolve dependenci
es for project net.technicpack:launcher:jar:4.0-0: The following artifacts could
 not be resolved: net.technicpack:launchercore:jar:2.0.0-SNAPSHOT, net.technicpa
ck:launcheruicore:jar:1.0-SNAPSHOT, net.technicpack:minecraftcore:jar:1.0.0-SNAP
SHOT: Could not find artifact net.technicpack:launchercore:jar:2.0.0-SNAPSHOT ->
 [Help 1]
[ERROR]

**Comment by laci200270** [comment]
You not built the depencies for this.

**Comment by Pyker** [comment]
This no longer happens now that this is a monorepo
