### ISSUE TITLE
Don't wait for analytics responce before showing the launcher

### ISSUE THREAD

**Issue by PaintNinja** [TechnicPack/LauncherV3#52]
It is pretty common for some users to have ping times of over 500ms. The launcher could load up quicker if the analytics polling was done after the launcher has shown, rather than before, to speed up the load times a bit on slow connections.

**Comment by CannibalVox** [comment]
We haven't done launcher startup analytics for over a year.

**Comment by CannibalVox** [comment]
Well that's not true, over 6 months.

**Comment by PaintNinja** [comment]
Sorry my mistake, I meant querying the update stream. If the update stream was queried once the launcher was shown rather than during launcher load, load times could be improved. The disadvantage of this though would mean that launcher updates would be received every other launch, rather than every launch.

**Comment by CannibalVox** [comment]
I don't feel comfortable with that at all, sorry.

**Comment by PaintNinja** [comment]
Why not? My idea's similar to the current modpack update detection anyway...

**Comment by CannibalVox** [comment]
It would tie our hands in terms of our ability to update the API effectively, would make it more difficult for users to change update streams, and also is a crappy experience.  Every auto-updating app on the planet checks update status before launching, I'm sorry that the extra 200ms is killing your experience.

**Comment by PaintNinja** [comment]
Thank you for your clarification. I understand and agree with your decision
