### ISSUE TITLE
White screen on Linux

### ISSUE THREAD

**Issue by eduanb** [TechnicPack/LauncherV3#64]
Linux version displays a white page. This is likely due to setVisible() being called on JFrame before init is complete.
Example:
http://forums.technicpack.net/topic/119395-technic-launcher-white-screen-jframe-fails-to-paint/

**Comment by SunshineHunter** [comment]
This is a bug with the desktop environment GNOME, speaking of my own experience and others and confirmed by CanVox.

**Comment by eduanb** [comment]
I was using GNOME Ubuntu. Any update on a fix? I might have a look around to see if I could add a pull request.

**Comment by SunshineHunter** [comment]
This might help: http://forums.technicpack.net/topic/146700-launcher-doesnt-work-on-gnome3/
