### ISSUE TITLE
Solder on static websites! [Question/Suggestion/Request!]

### ISSUE THREAD

**Issue by Higgs1** [TechnicPack/LauncherV3#68]
Hello! 

**Edit SUMMARY (because...)**
A _very_ small change in the Technic Launcher could allow Solder modpacks to be hosted on static web server hosts! I'd like a dev's opinion on whether or not this is a direction they'd like to go in, or further steps that I could take. 

I was hoping to host a solder installation on a static web server, and according to the very few docs at http://docs.solder.io/docs, this should be possible ("should" be, because the docs aren't the most clear). Already I have successfully verified my static Solder install with technicpack.net using the undocumented /api/verify endpoint.

But then I ran into a strange error when trying to download my modpack in the launcher. It was blowing up when trying to read /api/modpack - it was getting a JSON object when it wanted a string instead when parsing the "modpacks" object. If the launcher could just allow both strings and objects when searching through the modpacks object, serving Solder from a static site would be possible.

I'm not sure if I should submit this request to the Technic Launcher or Solder projects, I guess because it depends on how you guys want the Solder API to look like. I also haven't looked at your other official Technic client implementations yet. But if you allow string and object keys in the /api/modpack modpacks object, Solder can be hosted on static sites! :)

Thanks~

**Comment by khionu** [comment]
1) I have no idea what you mean by "static web server", If it's static, it doesn't change, and that means definitely not PHP. If you can't run PHP on your web server..... you're out of luck, not to mention you *must* have command line access.

2) Of course it returns a JSON Object. The launcher needs more than a string.

3) The docs are thorough. There's nothing missing in there that you can't pull from prior experience as a server administrator, from the Technic Platform's interface, or the Digital Ocean docs that the Solder docs reference.

**Comment by khionu** [comment]
Oh.... and this should definitely have gone in the Solder Issue Tracker

**Comment by Higgs1** [comment]
Thanks for the response! :)

1) Correct on the point that static == doesn't change. Also true that I'm not using PHP, as I don't see any reason why (especially if I take the API docs literally). Incorrect that no PHP means I'm out of luck. I also have no idea why command line access is required?

2) The launcher seems to require a string value in the "modpacks" object on the non-full /api/modpack, not an object. Objects contained anywhere inside the "modpacks" object, even for keys that it doesn't need to know about in the non-full output crashes the launcher for some reason (probably because the devs didn't forsee anyone doing it not their way, which is all fine! That's why I opened this issue).

3) Links please? I see 0 documentation about the /api/verify endpoint, which is vital to getting anything done with Solder on the Technic Platform. The technic platform interface just gives a completely generic red error if /api/verify is not correct. The docs also mention the include=full parameter 0 times as far as I see, and it seems like it's used heavily, which is why I'm questioning this behavior. And because it's not the the API docs, that's why I opened this issue here.
Prior server administration experience probably might help, but I'm pretty unfamiliar with the mainstream Minecraft modding community, sorry :( I know other server admin stuff at least! 

Solder P.S.: possibly, but because it's not documented on the API docs (as far as I see, I probably missed a whole section of the docs), I'm not sure how the devs want the API to look, and the most direct change required would need to take place in the Launcher.

**Comment by khionu** [comment]
1) The docs tell you to install PHP and the whole setup is in PHP. It literally will not do anything unless you have PHP.

2) ..... you obviously don't know how to program

3) [This](http://docs.solder.io/docs/linking-solder-to-the-technic-platform) is literally everything you need for a functional Solder, in regards to linking Solder to the Platform.

Most of your issues are brought from the completely incorrect assumption you can have a web application without dynamic content. If docs tell you you need something, you need something. Including PHP.

Lastly, Solder has some of the best damn documentation I have ever seen. You need to learn what you're doing before you play with it.

**Comment by bochen415** [comment]
Some parts of the api are not discussed for security reasons.
Solder is available "as is". The user should make a setup so the platform can work with it. Not the other way around.
For more questions go to the technic dev discord server. The invite is in the docs.

**Comment by Higgs1** [comment]
@khionu 
1) Untrue, sorry :(
2) Completely untrue, don't make those fallacies because then I could just say you obviously don't know how to use a computer beyond posting on github, which is hopefully untrue.  My Github profile doesn't provide any evidence to support my claim though, but you still can't make your claim that I don't know how to code, that's not how it works.
3) Also completely untrue. That has very little to do with the Solder API unfortunately.

@bochen415 
Alright, thanks! So I did completely miss something. I'll be heading on over to the discord server to message them up. I still think it'd be neat if they could make this small change, I think it might open up some other neat possibilities too. 

Thanks to you both for your time!

**Comment by Higgs1** [comment]
Ouch jeez. I'd just like a dev's quick opinion on this.

**Comment by khionu** [comment]
You got 2 programmers and a Technic Moderator's take on it.

**Comment by khionu** [comment]
Not to mention, you're ignoring the forest for a single bloody tree

**Comment by Higgs1** [comment]
I may be ignoring the forest but I wanted to voice my opinion that I think it would be nice if modpack administrators could use a VCS and incremental downloads on a static web host, and I found that a very small change in the Technic launcher could make that possible.

On the Technic forums I see some people ask about where to find a free dynamic web host. I just believe that if static hosts were supported, that would ease some of those users, as static hosts seem to be very common. I understand there are some downsides to this however.

**Comment by khionu** [comment]
Technic does not have to cave to your desires. Your desires are for something that, you have been told by 3 people now, you do not understand.

$5 a month, with Digital Ocean, and you have a functioning server that you can use with Solder. Hell, shared web hosting with Console Access can cover this. Just because you want it free, doesn't mean an organization (that doesn't get paid for this) should make it easier for you.

**Comment by Higgs1** [comment]
Sorry, I understand my desires completely. Technic need not cave to my desires. I understand I am not entitled to a reply by a developer nor even a glance at it by any of them. I do not understand what further actions I should employ to bring this suggestion to the devs, as I see it as a worthy suggestion that gives more benefit than it's cost, although the value of it's benefit is disputed by 3, which is certainly to be expected. 

Under the assumption that the Technic organization wants to make it easy for people to play Minecraft modpacks, I believe this suggestion is worth their time to be considered. They may decide it is not worth their time to implement, but at the very least they themselves have weighed the option. If my assumption is at least partially incorrect and they just want to have fun, then I still consider this suggestion worthy of a glance from them.

**Comment by khionu** [comment]
I'm done. Continue being an idiot on someone else's time.

**Comment by Higgs1** [comment]
Please don't be so hostile, my goodness. Report button go!

**Comment by Higgs1** [comment]
I'm considering deleting this thread and re-creating it, to remove any distraction for new participants.

**Comment by AniMaid** [comment]
Perhaps you should consider them negative feedback instead of calling them distractions and trying to invalidate them

**Comment by Higgs1** [comment]
Yeah. So far my experience with team coding has been pretty different from this, but I still need experience!

**Comment by Isigiel** [comment]
Okay @Higgs1 I'll try to get all the way through this issue.
_according to the very few docs at http://docs.solder.io/docs, this should be possible ("should" be, because the docs aren't the most clear)_
If you may look at this http://i.imgur.com/P105MpD.png, you can see that the docs state very clearly, that php and some extensions are a **mus have** to run solder.
_Solder_ is a laravel-php application, that provides you with  user-interface, to save your modpacks into a database and aoffers an api for clients to get to that data.

I agree that the API-part of the docs is lacking most calls, only the calls providing information are discussed there, not any _service-calls_, but if you want to dig through the code, this https://github.com/TechnicPack/TechnicSolder/blob/master/app/controllers/ApiController.php is where all the API-calls are handled. Apart from that, the docs are for end-users who want to use _Technic-Solder_ as it is supposed to be used and do a good job teaching that.

I must admit that I have not yet understood what you are trying to do though, maybe you could describe your setup in greater detail and even give use a link to your _static solder_.

On to strings and objects. Solder gives all rsponses in JSON form, which is a way to store an object into a string, that makes it a little difficult for me to understand, why you would want to have the launcher accept strings. ( an example would be nice )

This issue tracker is correct, as I don't suppose you use solder at all.

On the topic of php: php is a requirement to use a php-app, I think we can agree on that, the API docs just tell you, what the php-app servers at some endpoints.

And after all, back to the _quick opinion_ I don't currently see what change you are proposing, if you could give examples for your response and the api response and highölight the difference, maybe people will get what exactly you are trying to do.

Discord was mentioned earlier (https://discord.gg/0Ehm7p0AD3QxzAKq) go inside the #help channel and feel free to ping me @Isigiel once you arrive, I'll try to get back on you then.

**Comment by disconsented** [comment]
Making solder static is impossible without loosing almost all of the functionality. It relies on being dynamic to be able to function, even if it were possible its not a small task. This is not a Nikola or Jekyll project.

**Comment by Higgs1** [comment]
@Isigiel Thanks for the detailed reply, I really appreciate it.

I agree, and I also believe I haven't made it clear that I understand, that the http://docs.solder.io/docs docs document the Solder-App very very well, and also do an excellent job helping end users with tutorials and descriptions and I wish documentation for other projects were as helpful and clear. I also think I understand (maybe not though) that the PHP Solder-App, and that app solely, is how it was intended to be used and the JSON interface doc is merely a convenience for people who need it.

I have also done a really poor job explaining myself too: I am not using the PHP Solder-App. I'm trying to set up a Solder-API compatible setup on a static web host, half because I think it would be fun and that half because I really believe static web hosts that preserve url path structure are much more common - including github, many blogging free sites, etc. And even where dynamic web hosts are readily available, serving static json (perhaps compiled) would be far less resource intensive than a whole PHP+composer setup that while looks pretty, and was probably fun to write, isn't required at all. 

I'll provide some examples, thanks!
So the current problem that's preventing me from reaching my goal is that the API uses an undocumented url parameter that doesn't seem necessary. Compare the two urls, one produces JSON strings, and the other produces JSON objects:
http://solder.technicpack.net/api/modpack (Strings)
http://solder.technicpack.net/api/modpack?include=full (Objects)

The first url is used by the Java Launcher client, which is why I opened this ticket. The second one is used by the http://www.technicpack.net/ client. 

Normally I'd say that because of this, my goal is "impossible" because it appears that the key names are matched to the modpack slug, so it would be impossible to have both a object and a string at the same key while being valid JSON. Changing the API would be a possibility at that point too but I would not ask for that. However, the Solder client at http://www.technicpack.net/ completely ignores the key. To retrieve information about a modpack, including the mods installed, it instead iterates over the "modpack" contents and searches for an object that has a "name" value equal to the modpack slug. The key of the value can be absolutely anything and it doesn't care. It also doesn't error when it gets a string value instead of an object inside the "modpacks" object. I understand why the include=full was implemented: it was to minimize requests sent to the Solder server in exchange for a slightly larger response sent, which is very reasonable assuming it's on a dynamic server.

There are a few possible solutions that I can think of:
1) Modify the launcher to accept both JSON strings and JSON objects in the result, and simply ignore the objects when it wants to iterate over the available modpack slug strings, and simply ignore the strings and use the "name" value of the objects to identify a modpack when it wants to get detailed info about a modpack. This solution seems really hacky, and even I personally don't like it. But! ** The http://www.technicpack.net/ already does this** This is what I was attempting to suggest in my OP but I did a super bad job.
2) Modify the API slighty:
2a) Only allow the non-full requests - remove include=full, always send JSON strings and require clients to fetch individual mod info by using the /api/modpack/<modpack slug> endpoint.
2b) Only allow the full requests - always send JSON objects and simply use the "name" field to get a list of available modpacks. This would result in more duplicate information, but fewer HTTP requests.
3) Say that static host support is not desired, and document the behavior of the vital include=full parameter on http://docs.solder.io/docs. 

I'll try to upload evidence that the http://www.technicpack.net/ behaves the way that I mentioned tomorrow, it's super late. I did have it able to read mods and mod versions while ignoring JSON strings, promise!

https://discord.gg/0Ehm7p0AD3QxzAKq is not working for me ATM :( It simply says, "The instant invite is invalid or has expired".

@disconsented If the API was changed, then of course it can easily be static. But as I mention above, http://www.technicpack.net/ already successfully reads the modpacks and modpack info without any changes to the API (I'll try to upload evidence of this tomorrow!). The only problem is a vital, undocumented behavior that the Java Launcher relies on. I've given a few possible solutions above so let me know if there's any functionality that would still be lost that I've missed.

**Comment by SunshineHunter** [comment]
I'll repeat it again: You **require** PHP with several extensions, Composer, a database, curl. Just get a cheap vps, and you are set as it doesn't require too much pc power! The devs will tell you the same everybody else said here.

Please close the issue.

**Comment by Isigiel** [comment]
@Higgs1 I hope that you can really close the issue after this comment.
The easy way to publish a pack on the platform is: upload a zip and link it.
Solder was and srill is a advanced way, oiginally only for technic and without any docs for the people who want to go the difficult way and think it'd worth the work.
Don't get me wrong I understand what you are trying to do and this could be done, but the GET parameter kills you, this is a completely valid way to query a API and it works great.
Also there are no docs on the solder API only docs on the solder app, which also give you an idea about the api endpoints that give the info.
If you find a way to somehow respond to the parameter have fun and good luck with your thing, but if not, you can't have a _static api_.

The solder API is only really specified by the solder app, meaning that everything the app does is kinda official api behaviour.
Sadly, there is no shared solder hosting for people not wanting to set up their own vps at the moment.

Leaving you with:
1. distribute your pack via a zip
2. use solder as it is
3. wait for eventual changes

I don't see any need to change the API just for a single person having a considerably weird idea, especially when there's a new version of the **API** alread in the makings, wich, btw, doesn't ave this feature anymore. And yes you heard me right, it's an API specification which is app-agnostic.
So maybe 4. is the right thing to do for you. And I hope you see why this issue needs closing now.

Cheers, Isigiel

**Comment by Higgs1** [comment]
Thanks for all the replies everyone :)

@Isigiel had the right answer
