### ISSUE TITLE
Modpack server download

### ISSUE THREAD

**Issue by The-Silver-Kid** [TechnicPack/LauncherV3#69]
There is not download button for modpack servers in the launcher.

**Comment by khionu** [comment]
No, but if you click on the Modpack Logo, it brings you to the Platform page for the Modpack, where it *will* be.

Just in case you aren't aware, Technic is currently without a Launcher Dev, so any changes to the Launcher, even if they agreed and would implement this, won't happen for a bit.

https://twitter.com/VoxTechnologie/status/690092248701259777

**Comment by The-Silver-Kid** [comment]
i am aware of that but it still seems ridiculous that i have to open the browser to get the file

**Comment by khionu** [comment]
I'm so sorry that you are required one additional click to get files that are not required for, nor enhance the experience of, the Modpack Launcher doing it's job of Launching a Modpack.

Have a lovely day/night.
