### ISSUE TITLE
SunCertPathBuilderException when using Let's Encrypt SSL

### ISSUE THREAD

**Issue by Ionaru** [TechnicPack/LauncherV3#71]
> _Original message from https://github.com/TechnicPack/TechnicSolder/issues/575_
> 
> Heya guys,
> 
> When serving my Solder installation with SSL encryption, the Technic client gives me this error:
> http://pastebin.com/unW5DwAe and it will not connect.
> 
> I used Let's Encrypt to generate the required certificate.

As this is more of an issue with the Launcher, I created a new issue to make you guys aware of a possible fix.

Let's Encrypt is not in the default Java keystore as of Java 8u77.

However there are ways to add a trusted certificate to the keystore in Java runtime.
I found a post on the Let's Encrypt community forums that might help with this -> https://community.letsencrypt.org/t/will-the-cross-root-cover-trust-by-the-default-list-in-the-jdk-jre/134/37

In my opinion it would be a good idea to add the Let's Encrypt to the keystore this way because more and more people use the Let's Encrypt certificates to provide secure websites.

**Comment by khionu** [comment]
Speaking realistically, this is something that should be handled by Oracle, rather than Technic patching it.

I would recommend writing a help article on the Technic Site, then linking it here. I can push it to the people who maintain the site for adding it to the Featured Help Docs on the ZenDesk, though no guarantees on them actually adding it.

**Comment by Ionaru** [comment]
It's true that this should be handled by Oracle, but waiting for them to put it in an update could take a very long time.
Patching it into the Technic Launcher would be relatively easy and it would allow me (and perhaps many others) to use Solder in a secure way. Besides, there's always the option of removing the patch once Oracle makes the necessary changes.

**Comment by khionu** [comment]
No, actually, it wouldn't. Even if Technic currently had a Launcher Dev

**Comment by Ionaru** [comment]
The way I see it is that the launcher just has to call the  AddRootCA() function once. Why would it be difficult?

**Comment by khionu** [comment]
I did a little research, and while it actually isn't that hard, it's not as simple as that. I doubted the ability to do that because it seems a huge security risk, in my perspective.

That said, my main point still stands. There is no Technic Launcher Dev at the time being.

**Comment by Ionaru** [comment]
And it doesn't help that there is no documentation on how to set up a dev environment for the launcher... :/

**Comment by khionu** [comment]
A good Java developer should be able to figure that out.

**Comment by Ionaru** [comment]
A good developer would have made documentation, but we're off topic now.

**Comment by khionu** [comment]
A good developer *who intended to have contributions*. Open Source doesn't necessarily mean they wanted the community to contribute.

**Comment by Olloth** [comment]
Hey guys.

The launcher uses a really really common build system in java called Maven.

You can argue that we're dumb and didn't provide enough documentation for how to get it set up, which is fair, but it's really 'common knowledge' that you can find easily by searching.

A typical strategy for learning how to build a package of any kind is:

* Look at the root directory for anything that looks like a build file
* Google it and find the build system and look at tutorials for how to set it up.

There is nothing really special needed for a dev environment for the launcher besides maven and the jdk. If you want to use an IDE (which I recommend for java), you can use eclipse or intellij, both of which have built in or easy to use maven support.

Unfortunately, if you do make this change for Technic (Which I have not been part of for over 2 years now) you have no one at the moment to accept the pull request, but something could probably be arranged.

**Comment by Ionaru** [comment]
It is also worth noting that you need 4 packages: [LauncherV3](https://github.com/TechnicPack/LauncherV3), [LauncherCore](https://github.com/TechnicPack/LauncherCore), [LauncherUICore](https://github.com/TechnicPack/LauncherUICore) and [MinecraftCore](https://github.com/TechnicPack/MinecraftCore). Use mvn clean install first for LauncherCore, then MinecraftCore, then LauncherUICore and finally LauncherV3.

However, the program will not build unless you comment out the JarSigner plugin in the LauncherV3 pom.xml.

**Comment by Pyker** [comment]
This is fixed now (fixed in a708aea044af67bd8071e7eb31a8a2abe18bba55)
