### ISSUE TITLE
Interface is miniscule on 4k monitor

### ISSUE THREAD

**Issue by skwerlman** [TechnicPack/LauncherV3#72]
the interface is the exact same size in pixels as it would be on a same-sized 1080p monitor, meaning it appears at 1/4 it's intended size, which makes it VERY hard to use.

**Comment by Ionaru** [comment]
Minecraft has an interface-size option in the video settings, try changing that to Large.

**Comment by CTXz** [comment]
I can absolutely relate and agree. The launcher does not scale as necessary for hiDPI displays.

**Comment by Pythonic-Rainbow** [comment]
To be frank , Java Swing sucks at doing so

**Comment by JimmyCushnie** [comment]
Still an issue in december 2020 :/ using technic is a huge pain in 4k

**Comment by JimmyCushnie** [comment]
Wtf? I restarted the launcher today and now it looks great lol. If someone fixed this and the client auto-updated, thank you very much to the fixer!

**Comment by Pyker** [comment]
There have been literally no changes, so that's interesting lol

**Comment by Pyker** [comment]
This is really just a problem with Java 8, which is all sorts of broken when it comes to hiDPI. The only real "solution" appears to be this workaround: https://www.netphantom.com/info/Java-DPI-aware/index.html

This is a related bug: https://bugs.openjdk.java.net/browse/JDK-8080153

**Comment by Pyker** [comment]
Closing this as it seems to no longer be an issue (at least with a decently recent JRE, even if it's Java 8).
