### ISSUE TITLE
Launcher Options > Java Settings > Java Args don't get passed to JVM

### ISSUE THREAD

**Issue by Dockter** [TechnicPack/LauncherV3#77]
Tested this setting in various ways can't seem to get the launcher to respect any arguments.  Verified with profiler, Process Explorer and log file.

**Comment by Lord-Ptolemy** [comment]
This was intentional from what I've been told. Which is stupid imho.

**Comment by bloodmc** [comment]
JVM args are handled here
https://github.com/TechnicPack/MinecraftCore/blob/master/src/main/java/net/technicpack/minecraftcore/launch/MinecraftLauncher.java#L156

**Comment by Dockter** [comment]
My fix for this is here:
https://github.com/AlmuraDev/MinecraftCore/commit/c0b97d11a0b72c18028a11f1d6ae3d7931be9eae

Problem is that you can't compile the Launcher and distribute it due to the fact that the Technic signs the jar.  Any un-signed jar traffic passed to the technic data core is denied.  Thus the launcher only half works.

**Comment by xemnes** [comment]
could i request this patch be pull requested and added to the offical launcher please? id really like this feature to work as i rely on it.

**Comment by Dockter** [comment]
I appreciate you taking the time to resolve this.

**Comment by Pyker** [comment]
Yeah, sorry about the delay.
